# Example configuration file

model:
  architecture: resnet50
  num_classes: 10
  learning_rate: 0.001
  batch_size: 64

data:
  dataset_path: /path/to/dataset
  train_split: 0.8
  validation_split: 0.1
  test_split: 0.1

training:
  num_epochs: 10
  log_interval: 100